version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-image-sample:latest
    env_file:
      - .env
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345
      SERVER_PORT: 8082
    ports:
      - "8082:8082"   # host:container
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core_ccm
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  db_data:
